### ISSUE TITLE
バイナリについて提案

### ISSUE THREAD

**Issue by ghost** [suin/kobito-cli#3]
リポジトリ内にバイナリファイルを含めてますがCIツールなどをを使用してgithubのreleasesにバイナリファイルを登録されたらどうですか？

**Comment by suin** [comment]
@39e ご提案ありがとうございます！ちょっと手抜きでしたね^^; CIツール探してみて良さそうなのがあれば導入してみようと思います。

**Comment by ghost** [comment]
[CircleCi](http://circleci.com) であれば [こんな感じ](https://git.io/vXqEQ) のファイルを追加して `$GITHUB_TOKEN` を設定すると自動で作ってくれるようになりますよ
